<x-app-layout>
    <x-slot name="header"><div class="dashboard-heading event-heading"><div><p class="eyebrow">Yearbook office / stories</p><h1>Campus events</h1></div>@if(in_array(Auth::user()->role?->role_name,['admin','editor']))<a href="{{ route('events.create') }}" class="button button-red"><span aria-hidden="true">+</span> Add event</a>@endif</div></x-slot>
    @php $statusCounts=\App\Models\Event::query()->when(Auth::user()->role?->role_name==='reviewer',fn($q)=>$q->where('status','!=','draft'))->selectRaw('status, COUNT(*) as total')->groupBy('status')->pluck('total','status'); $isReviewer=Auth::user()->role?->role_name==='reviewer'; @endphp
    <div class="dashboard-wrap event-wrap" x-data="{search:'',status:'{{ request('status','all') }}',year:'{{ request('year','all') }}',campus:'{{ request('campus','all') }}',school:'{{ request('school','all') }}'}">
        <section class="event-intro"><div><p class="eyebrow eyebrow-light">The year in motion</p><h2>Capture campus<br>in the moment.</h2><p>Keep the stories, gatherings, and milestones that bring this year's yearbook to life.</p></div><div class="event-intro-mark" aria-hidden="true">EVENTS<br><span>{{ $events->total() }}</span></div></section>
        @if(session('success')||session('error'))<div class="notice {{ session('error')?'notice-error':'notice-success' }}">{{ session('error')??session('success') }}</div>@endif
        <section class="filter-ribbon" aria-label="Event filters"><div class="filter-ribbon-heading"><div><p class="eyebrow">Filter events</p><span>Focus the story calendar by edition or place.</span></div><a href="{{ route('events.index') }}" class="clear-filters">Clear filters</a></div><div class="event-filters"><a href="{{ request()->fullUrlWithQuery(['status'=>null,'page'=>1]) }}" class="filter-button {{ request('status','all')==='all'?'is-selected':'' }}">All <span>{{ \App\Models\Event::query()->when($isReviewer,fn($q)=>$q->where('status','!=','draft'))->count() }}</span></a>@foreach(['draft'=>'Draft','reviewed'=>'Submitted for review','approved'=>'Approved','published'=>'Published','rejected'=>'Changes requested'] as $key=>$label)@continue($key==='draft'&&$isReviewer)<a href="{{ request()->fullUrlWithQuery(['status'=>$key,'page'=>1]) }}" class="filter-button {{ request('status')===$key?'is-selected':'' }}">{{ $label }} <span>{{ $statusCounts->get($key,0) }}</span></a>@endforeach</div><div class="ribbon-fields"><select class="directory-filter" x-model="year" @change="window.location='{{ route('events.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)"><option value="all">All years</option>@foreach($academicYears as $academicYear)<option value="{{ $academicYear->id }}">{{ $academicYear->title }}</option>@endforeach</select><select class="directory-filter" x-model="campus" @change="window.location='{{ route('events.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)"><option value="all">All campuses</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}">{{ $campus->name }}</option>@endforeach</select><select class="directory-filter" x-model="school" @change="window.location='{{ route('events.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)"><option value="all">All schools</option>@foreach($schools as $school)<option value="{{ $school->id }}">{{ $school->name }}</option>@endforeach</select></div></section>
        <section class="event-toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><input type="search" x-model="search" placeholder="Search events"></label></section>
        <section class="event-section"><div class="section-heading"><div><p class="eyebrow">Story calendar</p><h2>Campus moments</h2></div><span class="panel-meta">{{ $events->total() }} records</span></div>
            <div class="event-grid">
                @forelse($events as $event)
                @php $searchText=strtolower($event->title.' '.($event->category?->name??'').' '.($event->location??'').' '.($event->description??'')); @endphp
                <article class="event-card" x-show="@js($searchText).includes(search.toLowerCase())">
                    <div class="event-card-top"><span class="event-date"><strong>{{ \Carbon\Carbon::parse($event->event_date)->format('d') }}</strong><small>{{ \Carbon\Carbon::parse($event->event_date)->format('M Y') }}</small></span><span class="edition-status {{ $event->status==='published'?'is-active':'is-archived' }}">{{ $event->status==='reviewed'?'Submitted for review':($event->status==='rejected'?'Changes requested':ucfirst($event->status)) }}</span></div>
                    <p class="event-category">{{ $event->category?->name??'Campus story' }}@if($event->featured)<span>Featured</span>@endif</p><h3>{{ $event->title }}</h3><p class="event-location">{{ $event->location?:'Location to be announced' }} · {{ $event->academicYear?->title??'No academic year' }}</p>@if($event->description)<p class="event-description">{{ \Illuminate\Support\Str::limit($event->description,150) }}</p>@endif
                    @if($event->reviewFeedback->count())<div style="margin:12px 0;padding:10px;background:#fff8f0;border:1px solid #f1d6b2;border-radius:9px;font-size:12px;"><strong>{{ $event->reviewFeedback->count() }} open review note{{ $event->reviewFeedback->count()>1?'s':'' }}</strong><br><span style="color:#64748b;">{{ \Illuminate\Support\Str::limit($event->reviewFeedback->first()->message,90) }}</span></div>@endif
                    <div class="event-footer"><a href="{{ $isReviewer?route('reviews.events.show',$event):route('events.edit',$event) }}" class="text-link">{{ $isReviewer?'Review event':'Open event' }} →</a>@if(!$isReviewer)<form method="POST" action="{{ route('events.destroy',$event) }}">@csrf @method('DELETE')<button type="submit" class="text-button">Delete</button></form>@endif</div>
                    <div class="event-actions">
                        @if($event->status==='draft'&&!$isReviewer)<form method="POST" action="{{ route('events.submit',$event) }}">@csrf<button type="submit" class="action-button action-primary">Submit for review</button></form>
                        @elseif($event->status==='reviewed'&&in_array(Auth::user()->role?->role_name,['admin','reviewer']))<a href="{{ route('reviews.events.show',$event) }}" class="action-button action-primary">Review event</a>
                        @elseif($event->status==='approved'&&in_array(Auth::user()->role?->role_name,['admin','reviewer']))<form method="POST" action="{{ route('events.publish',$event) }}">@csrf<button type="submit" class="action-button action-primary">Publish event</button></form>
                        @elseif($event->status==='rejected'&&!$isReviewer)<form method="POST" action="{{ route('events.submit',$event) }}">@csrf<button type="submit" class="action-button action-primary">Resubmit for review</button></form>@endif
                        @if(!$event->aiGenerations->count()&&in_array(Auth::user()->role?->role_name,['admin','editor']))<form method="POST" action="{{ route('events.generate-summary',$event) }}">@csrf<button type="submit" class="action-button">Generate summary</button></form>@endif
                    </div>
                </article>
                @empty<div class="empty-editions"><p class="eyebrow">No events yet</p><h3>Start the story calendar.</h3><p>Add a campus event to begin building this year's collection.</p>@if(!$isReviewer)<a href="{{ route('events.create') }}" class="button button-navy">Add event →</a>@endif</div>@endforelse
            </div>
            @if($events->hasPages())<div class="liu-pagination" aria-label="Events pagination"><div class="liu-pagination-summary">Showing <strong>{{ $events->firstItem() }}</strong>–<strong>{{ $events->lastItem() }}</strong> of <strong>{{ $events->total() }}</strong></div><div class="liu-pagination-controls">@if($events->onFirstPage())<span class="liu-page-arrow is-disabled">←</span>@else<a class="liu-page-arrow" href="{{ $events->previousPageUrl() }}">←</a>@endif @foreach($events->onEachSide(1)->getUrlRange(max(1,$events->currentPage()-1),min($events->lastPage(),$events->currentPage()+1)) as $page=>$url)<a href="{{ $url }}" class="liu-page-number {{ $page==$events->currentPage()?'is-current':'' }}">{{ $page }}</a>@endforeach @if($events->hasMorePages())<a class="liu-page-arrow" href="{{ $events->nextPageUrl() }}">→</a>@else<span class="liu-page-arrow is-disabled">→</span>@endif</div></div>@endif
        </section>
    </div>
</x-app-layout>