<x-app-layout>
    <x-slot name="header"><div class="dashboard-heading graduate-heading"><div><p class="eyebrow">Yearbook office / people</p><h1>Graduate profiles</h1></div>@if (in_array(Auth::user()->role?->role_name, ['admin','editor']))<div style="display:flex;gap:10px;flex-wrap:wrap;"><a href="{{ route('graduates.import') }}" class="button button-navy"><span aria-hidden="true">↥</span> Import graduates</a><a href="{{ route('graduates.create') }}" class="button button-red"><span aria-hidden="true">+</span> Add graduate</a></div>@endif</div></x-slot>
    <div class="dashboard-wrap graduate-wrap" x-data="{ search:'{{ request('search','') }}', status:'{{ request('status','all') }}', year:'{{ request('year','all') }}', campus:'{{ request('campus','all') }}', school:'{{ request('school','all') }}', major:'{{ request('major','all') }}' }">
        <section class="graduate-intro"><div><p class="eyebrow eyebrow-light">The people behind the year</p><h2>Make every<br>story count.</h2><p>Review, refine, and publish the voices that will define this year's yearbook.</p></div><div class="graduate-intro-stats"><div><strong>{{ $graduates->total() }}</strong><span>profiles</span></div><div><strong>{{ $consentGranted }}</strong><span>consents</span></div></div></section>
        @if(session('success') || session('error'))<div class="notice {{ session('error')?'notice-error':'notice-success' }}">{{ session('error') ?? session('success') }}</div>@endif
        <section class="filter-ribbon" aria-label="Graduate profile filters"><div class="filter-ribbon-heading"><div><p class="eyebrow">Filter profiles</p><span>Focus the directory by edition, place, or discipline.</span></div><a href="{{ route('graduates.index') }}" class="clear-filters">Clear filters</a></div><div class="graduate-filters"><a href="{{ request()->fullUrlWithQuery(['status'=>null,'page'=>1]) }}" class="filter-button {{ request('status','all')==='all'?'is-selected':'' }}">All <span>{{ $statusCounts->sum() }}</span></a>@foreach(['draft'=>'Draft','reviewed'=>'Submitted for review','approved'=>'Approved','published'=>'Published','rejected'=>'Changes requested'] as $key=>$label)<a href="{{ request()->fullUrlWithQuery(['status'=>$key,'page'=>1]) }}" class="filter-button {{ request('status')===$key?'is-selected':'' }}">{{ $label }} <span>{{ $statusCounts->get($key,0) }}</span></a>@endforeach</div><div class="ribbon-fields"><select class="directory-filter" x-model="year" name="year" @change="window.location='{{ route('graduates.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)+'&major='+encodeURIComponent(major)+'&search='+encodeURIComponent(search)"><option value="all">All years</option>@foreach($academicYears as $academicYear)<option value="{{ $academicYear->id }}">{{ $academicYear->title }}</option>@endforeach</select><select class="directory-filter" x-model="campus" name="campus" @change="window.location='{{ route('graduates.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)+'&major='+encodeURIComponent(major)+'&search='+encodeURIComponent(search)"><option value="all">All campuses</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}">{{ $campus->name }}</option>@endforeach</select><select class="directory-filter" x-model="school" name="school" @change="window.location='{{ route('graduates.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)+'&major='+encodeURIComponent(major)+'&search='+encodeURIComponent(search)"><option value="all">All schools</option>@foreach($schools as $school)<option value="{{ $school->id }}">{{ $school->name }}</option>@endforeach</select><select class="directory-filter" x-model="major" name="major" @change="window.location='{{ route('graduates.index') }}?status='+encodeURIComponent(status)+'&year='+encodeURIComponent(year)+'&campus='+encodeURIComponent(campus)+'&school='+encodeURIComponent(school)+'&major='+encodeURIComponent(major)+'&search='+encodeURIComponent(search)"><option value="all">All majors</option>@foreach($majors as $major)<option value="{{ $major->id }}">{{ $major->name }}</option>@endforeach</select></div></section>
        <section class="graduate-toolbar"><form method="GET" action="{{ route('graduates.index') }}"><input type="hidden" name="status" x-model="status"><input type="hidden" name="year" x-model="year"><input type="hidden" name="campus" x-model="campus"><input type="hidden" name="school" x-model="school"><input type="hidden" name="major" x-model="major"><label class="search-field"><span aria-hidden="true">⌕</span><input type="search" name="search" x-model="search" value="{{ request('search','') }}" placeholder="Search by name, school, or major"></label></form></section>
        <section class="graduate-section"><div class="section-heading"><div><p class="eyebrow">Profile directory</p><h2>Class of graduates</h2></div><span class="panel-meta">{{ $graduates->total() }} records</span></div>
            <div class="graduate-grid" :class="{ 'graduate-list':view==='list' }">
                @forelse($graduates as $graduate)
                @php $searchText=strtolower($graduate->name.' '.($graduate->school?->name??'').' '.($graduate->major?->name??'').' '.($graduate->student_reference??'')); $graduateYearIds=collect([$graduate->academic_year_id,$graduate->graduation?->academic_year_id])->filter()->map(fn($id)=>(string)$id)->values()->all(); $initials=collect(explode(' ',trim($graduate->name)))->filter()->map(fn($part)=>strtoupper(substr($part,0,1)))->take(2)->implode(''); $isReviewer=Auth::user()->role?->role_name==='reviewer'; @endphp
                <article class="graduate-card" x-show="(status==='all'||status==='{{ $graduate->publish_status }}')&&(year==='all'||@js($graduateYearIds).includes(year))&&(campus==='all'||campus==='{{ $graduate->campus_id }}')&&(school==='all'||school==='{{ $graduate->school_id }}')&&(major==='all'||major==='{{ $graduate->major_id }}')&&@js($searchText).includes(search.toLowerCase())">
                    <div class="graduate-card-top">@if($graduate->portraitMedia)<img class="graduate-avatar graduate-avatar-photo" src="{{ Storage::disk('public')->url($graduate->portraitMedia->path) }}" alt="{{ $graduate->portraitMedia->alt_text??$graduate->name }}">@else<div class="graduate-avatar">{{ $initials }}</div>@endif<span class="edition-status {{ $graduate->publish_status==='published'?'is-active':'is-archived' }}">{{ $graduate->publish_status==='reviewed'?'Submitted for review':($graduate->publish_status==='rejected'?'Changes requested':ucfirst($graduate->publish_status)) }}</span></div>
                    <h3>{{ $graduate->name }}</h3><p class="graduate-reference">{{ $graduate->student_reference?:'No student reference' }}</p><dl class="graduate-details"><div><dt>School</dt><dd>{{ $graduate->school?->name??'Unassigned' }}</dd></div><div><dt>Major</dt><dd>{{ $graduate->major?->name??'Unassigned' }}</dd></div><div><dt>Campus</dt><dd>{{ $graduate->campus?->name??'Unassigned' }}</dd></div></dl>
                    @if($graduate->reviewFeedback->count())<div style="margin:12px 0;padding:10px;background:#fff8f0;border:1px solid #f1d6b2;border-radius:9px;font-size:12px;"><strong>{{ $graduate->reviewFeedback->count() }} open review note{{ $graduate->reviewFeedback->count()>1?'s':'' }}</strong><br><span style="color:#64748b;">{{ \Illuminate\Support\Str::limit($graduate->reviewFeedback->first()->message,90) }}</span></div>@endif
                    <div class="graduate-footer"><span class="consent-label"><span class="status-dot {{ $graduate->consent_status==='granted'?'status-approved':'status-reviewed' }}"></span>{{ ucfirst($graduate->consent_status?:'pending') }} consent</span><a href="{{ $isReviewer?route('reviews.graduates.show',$graduate):route('graduates.edit',$graduate) }}" class="text-link">{{ $isReviewer?'Review profile':'Open profile' }} <span aria-hidden="true">→</span></a></div>
                    <div class="graduate-actions">
                        @if($graduate->publish_status==='draft'&&!$isReviewer)<form method="POST" action="{{ route('graduates.submit',$graduate) }}">@csrf<button type="submit" class="action-button action-primary">Submit for review</button></form>
                        @elseif($graduate->publish_status==='reviewed'&&in_array(Auth::user()->role?->role_name,['admin','reviewer']))<a href="{{ route('reviews.graduates.show',$graduate) }}" class="action-button action-primary">Review profile</a>
                        @elseif($graduate->publish_status==='approved'&&in_array(Auth::user()->role?->role_name,['admin','reviewer']))<form method="POST" action="{{ route('graduates.publish',$graduate) }}">@csrf<button type="submit" class="action-button action-primary">Publish profile</button></form>
                        @elseif($graduate->publish_status==='rejected'&&!$isReviewer)<form method="POST" action="{{ route('graduates.submit',$graduate) }}">@csrf<button type="submit" class="action-button action-primary">Resubmit for review</button></form>@endif
                    </div>
                </article>
                @empty<div class="empty-editions"><p class="eyebrow">No profiles yet</p><h3>Start the class directory.</h3><p>Add a graduate to begin shaping this year's collection.</p>@if(!$isReviewer)<a href="{{ route('graduates.create') }}" class="button button-navy">Add graduate →</a>@endif</div>@endforelse
            </div>
            @if($graduates->hasPages())<div class="liu-pagination" aria-label="Graduate pagination"><div class="liu-pagination-summary">Showing <strong>{{ $graduates->firstItem() }}</strong>–<strong>{{ $graduates->lastItem() }}</strong> of <strong>{{ $graduates->total() }}</strong></div><div class="liu-pagination-controls">@if($graduates->onFirstPage())<span class="liu-page-arrow is-disabled">←</span>@else<a class="liu-page-arrow" href="{{ $graduates->previousPageUrl() }}">←</a>@endif @foreach($graduates->getUrlRange(max(1,$graduates->currentPage()-1),min($graduates->lastPage(),$graduates->currentPage()+1)) as $page=>$url)<a href="{{ $url }}" class="liu-page-number {{ $page==$graduates->currentPage()?'is-current':'' }}">{{ $page }}</a>@endforeach @if($graduates->hasMorePages())<a class="liu-page-arrow" href="{{ $graduates->nextPageUrl() }}">→</a>@else<span class="liu-page-arrow is-disabled">→</span>@endif</div></div>@endif
        </section>
    </div>
</x-app-layout>